name: gtm_py11
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - contourpy=1.2.0
  - cycler=0.11.0
  - faiss=1.7.4
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=16.0.6
  - libdeflate=1.17
  - libexpat=2.5.0
  - libfaiss=1.7.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.44.2
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - munkres=1.1.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openjpeg=2.3.0
  - openssl=3.2.0
  - packaging=23.1
  - pandas=2.1.4
  - pillow=10.0.1
  - pip=23.3.1
  - pyparsing=3.0.9
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - readline=8.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - wordcloud=1.9.2
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5